### ISSUE TITLE
Why `= default` constructors?

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#16]
@jensmaurer:
> (26) datapar and mask default constructors are "= default", but you say elsewhere you want zero-initialization of the values.  Better remove the =default and say that explicitly.

Right. I guess I worded this incorrectly. What I want is `datapar<T> x;`: `x` is uninitialized, `datapar<T>()`: zero-initialized. AFAIK, the only way to achieve this is with a default default constructor. Since there are other ctors it needs an explicitly defaulted default ctor.

Do you have a suggestion how to word this?

**Comment by jensmaurer** [comment]
Ah ok. Then, leave the =default and still say that explicitly after the class synopsis. Something like "default initialization performs no initialization on the elements; value-initialization initializes each element with T()".

**Comment by mattkretz** [comment]
I dropped the default ctor itemdecl and itemdescr. Added a paragraph in the overview sections:
"Default initialization should not perform any initialization on the elements; value-initialization shall initialize each element with T()." (or bool() for [mask.overview])

I deliberately chose "should" and "shall" here. I'm afraid a "shall" on both parts makes this requirement too complicated for some targets. What do you think?

**Comment by jensmaurer** [comment]
Since it's undefined behavior to inspect an indeterminate value (which is the result of "not initializing"), it's not observable whether the implementation actually did initialize or not.

Plus, LWG seems to gravitate towards the CWG position that "shall" (without "implementation") establishes constraints on user code. My wording suggestion for the overview sections:

> 
Default initialization performs no initialization of the elements; value-initialization initializes each element with T(). [ Note: Thus, default initialization leaves the elements in an indeterminate state. -- end note ]

**Comment by mattkretz** [comment]
OK. So my concern just boils down to a QoI issue. Fine. Thanks for the words. You have good words. ;-)
