### ISSUE TITLE
allow << and <<= overloads with scalar on RHS

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#28]
@jensmaurer: Some SIMD instruction sets (notably on x86) do not have hardware support for shifts where the right hand side is a vector argument. However, if an instruction with a scalar shift exists then `datapar<int> << int` should not translate to `datapar<int> << datapar<int>(int)` and thus fall back to a loop over scalar shifts.

Two options for the wording:
1. Explicitly add an overload with a scalar RHS. The type of the RHS should probably just be `int` and not some complicated SFINAE like a broadcast ctor otherwise implies.
2. Add wording to allow an additional overload for optimizing this case. I guess this implies that this overload may not change overload resolution outcome and thus require the same semantics for the RHS type as the broadcast ctor would require.

What do you think?
And should I add it to the draft before Kona or should we postpone it to a new paper?

**Comment by jensmaurer** [comment]
AVX2 or so seems to have `vpsllvd`, which does a vector-by-vector variable shift.

Further, gcc 6.3.0 seems to be able to optimize a vector shifted by a same-element vector

```
typedef int intv __attribute__((vector_size(16)));
intv x;
int y1;
int main()
{
  const intv y = { y1, y1, y1, y1 };
  x = x << y;
  return x[1];
}
```

to `pslld`.

Hm... Just a plain "int" overload would do it, I'd say, and avoid the broadcast vs. optimizer effort. (I suspect that other architectures can also do something smarter / more efficient when shifting by a scalar.)

The issue I have with "int" is that values less than 0 are undefined behavior (really?) and values less than the width are also undefined behavior (really?). So, isn't using "unsigned int" as the parameter type the better option? For int compile-time constants, it just works without a warning; for "int" variables, maybe the conversion warning helps you understand there's a very limited domain. That said, some people believe in "ints everywhere unless you need something else". However, if we offer both "int" and "unsigned int" overloads, we also need to offer all larger-sized overloads, because a "long" converts to both an "int" and an "unsigned int" equally well (or equally bad).

**Comment by mattkretz** [comment]
https://godbolt.org/g/TLxkq7 Wow, Clang has a nice trick up its sleave. But yes, one could certainly argue that the `int` overload can be omitted because compilers are (and ICC "should be") smart. But OTOH I don't like to throw away useful information about an operation, just because the optimizers are heros. It might just fail to work for a corner case that's important to someone.

I agree `int` vs. `unsigned int` doesn't help much in terms of inhibiting UB usage. I also believe in "default to `int`; argue for unsigned if you need modulo arithmetics or work on bits". And I agree, having `int` and `unsigned` overloads is going to annoy more than it helps.

I'll add the `int` overload to the R4 draft.

**Comment by jensmaurer** [comment]
Oh, the Clang idea is very nice here: Convert the shift count to a floating-point exponent and convert back to an integer factor, thereby essentially using the floating-point shift machinery in the guts. Cool.
