### ISSUE TITLE
*find better names*

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/wg21-papers#42]
names for
* `datapar`
  * `vector<T>`
  * `vec<T>`
  * `simd<T>`
  * `datapar<T>`
  * `pack<T>`
  * `simdarray<T>`
  * `simdvector<T>`
  * `vecarray<T>`
  * `vectorize<T>`
  * `simdize<T>`
* `mask`
  * `mask<T>`
  * `vecmask<T>`
  * `simdmask<T>`
  * `boolvec<T>`
* `where`
* `memload`, `memstore`

**Comment by mattkretz** [comment]
## Renaming `datapar`

### `vector`
The obvious choice for the name is `vector`. That's the term of the art. We talk about "vectorization", "vector unit", "vector registers", ... The obvious reason for that being a bad name is `std::vector` and the ambiguity with mathematically inclined people who have a different connotation for something that is called vector and defines mathematical operators.

### `vec`

### `vec<something>`

### `simd`

### `pack`

###

**Comment by jensmaurer** [comment]
also consider renaming "mask"

**Comment by jensmaurer** [comment]
Other proposal for "datapar": simd_vector, simd_array

I'd like to have concise "pro" and "con" sections for each proposed name. Feel free to delete my comments once you've integrated them above.

Since we only define a few (global) names and lots of operators, I'd like to suggest we find names that can go directly into namespace std. Or is there a desire to have a namespace std::simd ?

`vector`
pro: term-of-art in the industry (see your text above); does work as a mathematical vector, e.g. `std::reduce<std::plus>(x*y)` is the scalar product.
con: Too much confusion/conflict with std::vector, which is not constant-size.

`simd_array`
pro: matches constant-length std:array and math-style of std::valarray.
con: a bit long for daily use; has ugly underscore

`simd`
pro: short; pronouncible; usage is idiomatic: `simd<T>` is the SIMD thing for T. Known term in the industry; maybe even more to the point than "vector" (note variable-length vector units on traditional vector computers)
con: acronym

`pack`
pro: short; prononcible; usage is somewhat idiomatic.
con: Conflicts with "template parameter pack" usage in variadic templates. These tend to appear in the same context: "You can have a [template parameter] pack of packs [types]." (what?)

`vec`
pro: short, pronouncible; usage is somewhat idiomatic: `vec<T>` is a vector-lookalike of T.
con: abbreviation; too close to "std::vector"

-> I like "simd".

**Comment by mattkretz** [comment]
Regarding `mask`: I think the term is very clear in connection with the "datapar" type. However, in isolation it may certainly lead to head-scratching. If the `mask` class were a member of the "datapar" class (i.e. namespaced) it would be much clearer.

I expected to have the types go directly into the `std` namespace. Should we have a discussion of this choice?

**Comment by jensmaurer** [comment]
Regarding mask: Hm... I think exposing the mask as a member-of-datapar (only) is not going to work, because it prevents template argument deduction for users when they need it. We need a standalone exposed mask type.

**Comment by mattkretz** [comment]
> mask as a member-of-datapar (only) [...] prevents template argument deduction

true. So that's off the table.

I started to brainstorm names in the top comment of this thread. If you have any more ideas, just add to the thread

**Comment by mattkretz** [comment]
Feel free to edit https://github.com/mattkretz/wg21-papers/blob/master/P0214/naming.md if you have more ideas/thoughts.

**Comment by mattkretz** [comment]
Also, I started https://github.com/mattkretz/wg21-papers/blob/master/naming-checklist.md to collect some criteria for short-listing the name options.

**Comment by mattkretz** [comment]
@jensmaurer Please review the "Naming" section in https://web-docs.gsi.de/~mkretz/datapar.pdf. Do you have any comments how to improve this section?

**Comment by jensmaurer** [comment]
Looks reasonable to me. As far as I can see, it's only the "datapar" thing where you don't give a clear (personal) preference.

**Comment by mattkretz** [comment]
> As far as I can see, it's only the "datapar" thing where you don't give a
> clear (personal) preference.

Yes. You may consider the short list in order of preference, though. But 
really I don't feel confident to choose the name here.

**Comment by mattkretz** [comment]
I expanded the discussion on "mask queries", i.e. bit operations, to include your P0553 paper:
![grafik](https://user-images.githubusercontent.com/3306474/27276503-bed9a79c-54db-11e7-95ad-64bd41bcf1b2.png)

I think the section is ready for LEWG discussion at this point.

**Comment by jensmaurer** [comment]
Looks good to me.
